### ISSUE TITLE
Pretrained weight release

### ISSUE THREAD

**Issue by ByeongHyunPak** [yinboc/infd#1]
Hi, I'm interested in your impressive work!
Can you please provide me with pre-trained weight to turn the demo around?

Thank you :)

**Comment by yinboc** [comment]
Yes, we will release it in the next few weeks.

**Comment by Njasa2k** [comment]
> Yes, we will release it in the next few weeks.

is it released?

**Comment by HireTheHero** [comment]
+1

**Comment by LouisSerrano** [comment]
Hi, I am interested too ! Great work by the way 🚀

**Comment by olliacc** [comment]
> Yes, we will release it in the next few weeks.

any update @yinboc

**Comment by DylanTao** [comment]
+1

**Comment by yinboc** [comment]
The models weights are now released in "Pretrained models" section.

The FFHQ training configs are also updated a bit to follow the original paper's setting. Note the training results has some variance if you train from scratch.

Thank you for your patience!

**Comment by yinboc** [comment]
The model weights are now released in "Pretrained models" section in this repo.

The FFHQ training configs are also updated a bit to follow the original paper's setting. Note the training results have some variance if you train from scratch.

Thank you for your patience!
